# -*- coding: utf-8 -*-
"""(실습용)_사용자_정의_함수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AnM8xXbf6AhitaAejpcVsRoNSSVn7ILd
"""







"""[sklearn 라이브러리 내부 코드](https://github.com/scikit-learn/scikit-learn)

---



---


# 사용자 정의 함수란?

- 내장 함수 : 파이썬을 설치하기만 하면 바로 사용할 수 있는 함수
<br/> ex. print(), input() 등

- 사용자 정의 함수 : 파이썬을 설치와 동시에 사용할 수 있는 명령어는 아니지만, 프로그램을 작성하는 사용자가 직접 만드는(정의하는) 명령어

ex. 게임 단축키에서 직진하기는 ctrl+G, 공격하기는 crtl+alt+enter
<br/> "직진 후 공격"을 동시에 수행하는 단축키를 만들기 ctrl+A

# 1. 사용자 정의 함수 사용법

#### Step 1. 사용자 정의 함수 만들기 (=정의하기)

```
def 함수이름() :
    함수 내용
```

#### Step 2. 만든 사용자 정의 함수 사용하기 (=호출하기)


```
함수이름()
```
"""

# 사용자 정의 함수 정의
def hi():
  print('hi')
  print('My name is Python')

# 사용자 정의 함수 호출
hi()

hi()
hi()

"""**step1. 함수 정의 --> step2. 함수 호출**

<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/112_%EC%82%AC%EC%9A%A9%EC%9E%90%EC%A0%95%EC%9D%98%ED%95%A8%EC%88%98.png?raw=true' width=600>

# 2. 사용자 정의 함수의 입출력

## 2-1. 사용자 정의 함수에 데이터 전달하기
> Q. print('hello!')처럼 함수 괄호 안에 데이터를 전달할 수는 없을까?

```
def 함수이름(매개변수) :
    함수 내용
```
매개변수란, 함수 외부의 데이터를 전달받는 변수
<br/>(= 함수 외부와 내부를 매개하는 변수)
"""

# 이름을 전달하면, 정해진 포맷에 맞춰 자기소개하는 함수
def hi(name):
  print('hi')
  print('My name is',name)

hi("응우옌")

"""<img src= 'https://github.com/teacher-jiejie/allinone_AI/blob/images/113_%EC%82%AC%EC%9A%A9%EC%9E%90%EC%A0%95%EC%9D%98%ED%95%A8%EC%88%98_%EC%9D%B8%EC%9E%90.png?raw=true' width=800>"""



"""#### 매개변수 여러 개 만들기"""

def hi(name,job):
  print('hi')
  print('My name is',name,"and my job is",job)



# 함수 호출 시 매개변수 생략하기

# 매개변수를 생략할 때에는 순서에 유의하기

"""<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/114_%EC%82%AC%EC%9A%A9%EC%9E%90%EC%A0%95%EC%9D%98%ED%95%A8%EC%88%98_%EC%9C%84%EC%B9%98%EC%9D%B8%EC%9E%90.png?raw=true' width=700>"""



"""## 2-2. 사용자 정의 함수 내부의 데이터를 함수 밖으로 전달하기

"""

# 두 수를 더하는 사용자 정의 함수 plus

"""함수의 내부와 외부 구분하기
<br/>
<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/115_%EC%82%AC%EC%9A%A9%EC%9E%90%EC%A0%95%EC%9D%98%ED%95%A8%EC%88%98_return.png?raw=true' width=600>

<br/>
함수 내부의 값 result를 함수 외부에서도 확인할 수 없을까?


```
def 함수이름(매개변수) :
    함수 내용
    return 전달할 데이터
```

"""



"""<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/116_%EC%82%AC%EC%9A%A9%EC%9E%90%EC%A0%95%EC%9D%98%ED%95%A8%EC%88%98.png?raw=true' width=600>"""

# return 과 동시에 함수 실행이 종료됨

"""# 3. 사용자 정의 함수의 활용



```
국어, 영어, 수학 점수를 입력받아 환산점수를 계산하는 함수 작성하기

- 국어 30%, 영어 30%, 수학 40%
- 환산점수를 반환하기
```


"""

# 국어 99, 영어 80, 수학 72일때 환산점수는?

"""

```
만약 환산 점수가 80점 초과라면 합격, 80점 이하라면 탈락이라고 출력하기
```

"""

# 함수의 반환값을 변수에 저장하기

"""#### 여러 개의 값을 반환하기
```
국어, 영어, 수학 점수를 입력받아 환산점수를 계산하는 함수 작성하기

- 국어 30%, 영어 30%, 수학 40%
- 80점이 넘으면 합격(yes), 80점 이하라면 불합격(no)
- 환산점수와 합격 유무를 반환하기
```

"""





# 여러 반환값을 변수에 저장하기

"""# 4. 지역변수와 전역변수

### 4-1. 지역변수
* 특정 지역(함수 내부)에서만 사용됨
* 함수 내부에서 만들어진 변수


"""



"""<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/117_%EC%A7%80%EC%97%AD%EB%B3%80%EC%88%981.png?raw=true' width=600>
<br/>
<img src='https://github.com/teacher-jiejie/allinone_AI/blob/images/118_%EC%A7%80%EC%97%AD%EB%B3%80%EC%88%982.png?raw=true' width=600>
"""

# 지역변수에 저장된 값을 함수 외부에서 사용하려면
# return을 활용해 반환하기

"""### 4-2. 프로그램 전체에서 사용되는 전역변수
* 함수 외부에서 만들어진 변수
* 프로그램 전역에서 (함수 외부, 내부 가리지 않고) 사용됨
"""



"""-> 함수 내부에서 전역변수의 값을 읽을 수 있다."""



"""**-> 함수 내부에서 전역변수의 값을 읽을 수는 있지만 변경할 수는 없다.**

변경하고 싶으면 키워드 global을 붙여야 함
"""







"""#### 상벌점 사용자 정의 함수 reward_penalty()


```
# 매개변수
  상점, 벌점 종류 = kind
  점수 = points
```


"""



