# -*- coding: utf-8 -*-
"""20613이정현 반복문(for~20 ex19).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSaCBPrp3_Ew0Dx7uWC5lcPdt8pSTrgw

# ***반복문***
"""

for i in [1,2,3]:
  print("안녕하세요", i)

for i in range(0,10,1):
  print(i,end= ' ')

for i in range(1,10+1,1):
  print(i,end= ' ')

for i in range(1,10,2):
  print(i,end= ' ')

for i in range(20,1,-2):
  print(i,end= ' ')

for i in range(3):
  print("안녕하세요")

a = 10

for num in range(1,5,2):
  a+=num
print(a)

for i in range(3):
  print(i+1,'번째 학생의 성적 처리')

for i in range(1,21,1):
  if i%2==0:
    print(i,end = ' ')

a = 2
for i in range(1,10,1):
  c = a*i
  print(f"{a} x {i} = {c}")

sum = 0

for i in range(1,10+1,1):
  sum += i
  print("i의 값: ",i,"  =>  합계: ",sum)

sum = 0

for i in range(2,100+1,2):
  sum += i

print("1~100까지의 even_sum = ", sum)

fact = 10

for i in range(1,fact+1,1):
  fact *= i

print("10! = ",fact
      )

for i in range(5,100+1,5):
  print(i,end = "  ")
  if(i%35==0):
    print("")

n = int(input("정수를 입력하시오: "))

for i in range(1,n+1,1):
  if n%i==0:
    print(i,end = ' ')

a = 0
b = 1

for i in range(20):
  print(a, end = '  ')
  n = a+b

  a = b
  b = n

for x in range(1,41,1):
  if x%10==0:
    print('+',end = '')
  else:
    print('-',end = '')

x= 1

while x<41:
  if x%10==0:
    print('+',end = '')
  else:
    print('-',end = '')
  x+=1

print("*"*40)
print("센치(cm) 인치(inch) 피트(ft) 야드(yd)")
print("*"*40)
for cm in range(10,101,10):
  inch = cm * 0.393701
  ft = cm * 0.032808
  yd = cm * 0.010936

  print("%7d %8.1f %8.1f %8.1f" %(cm,inch,ft,yd))
print("*"*40)

