# -*- coding: utf-8 -*-
"""20613이정현_리스트메소드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u089kFWhBcItEP5G6zNH0uQJ2YccQp1_
"""

nums = [1,2,3,4]
nums.append(5)
print(nums)

nums.insert(2,99)
print(nums)

list1 = [1,2,3,4,5]
list2 = [10,11]
list1.extend(list2)
print(list1)

score = [88,95,70,100,99]
print("100의 위치: ",score.index(100)+1)

print(score.pop())
print(score.pop())
print(score)
print(score.pop(1))
print(score)

score = [88,95,70,100,99]
score.remove(99)
print("99 삭제 후 :",score)
score.sort()
print("리스트 정렬 후:",score)
score.sort(reverse = True)
print("리스트 정렬 후:",score)
score.clear()
print("리스트 삭제 후:",score)

list1 = ['a','bb','c','d','aaa','c','ddd','aaa','b','cc','d','aaa']
length = list1.count("bb")
length

mylist = ['사과','바나나','파인애플']
mylist
mylist.append('키위')
mylist
mylist.append('배')
mylist

for m in mylist:
  print(m)

scores = []
while True:
  score = int(input("성적을 입력하세요. (종료: -1)"))
  if score == -1:
    break;
  scores.append(score)
print(scores)

nums = []

for i in range(5):
  nums.append(int(input("숫자를 입력하세요. ")))
print(nums)
nums.sort
print(nums)

emails = [["kim","naver.com"],["hwang","hanmail.net"],["lee","korea.com"],["choi","gmail.com"]]

email_new = []
for email in emails:
  email_new.append(email[0]+"@"+email[1])

print(email_new)

fruits = ['apple','orange','banana']

for fruits in fruits:
  print(fruits)

s = "Hello"
for i in s:
  print(i,end="")

colors = ["빨간색","파란색","노란색","초록색"]

for color in colors:
  print("나는 %s을 좋아한다"%color)

numbers = [7,9,15,18,30,-3,7,12,-16,-12]
sum = 0
for number in numbers:
  sum+=number
print("합계 : ",sum)

score = [1,3,5,7,9,11,13]
cnt = 0
for num in score:
  if num<1:
    cnt+=1
    print(num,end=' ')
print("\n10보다 작은 수의 개수 : ",cnt)

# Commented out IPython magic to ensure Python compatibility.
qestions = ['tr_in','b_s','_axi','air_lane']
answer = ['a','u','t','p']
count = 0
for i in range(4):
  q = '%s 에서 밑줄( _ )안에 들어갈 알파벳은? '
#   %qestions[i]
  ans = input(q)
  if ans == answer[i]:
    print("정답입니다!")
    count+=1
  else:
    print("틀렸습니다")
print("당신의 점수는 %d/4입니다" %count)

score = []
for i in range(5):
  num = int(input("성적입력: "))
  score.append(num)
print(score)

sum = 0
for s in score:
  sum+=s
print("총점은 %d이고 평균은 %.2f입니다."%(sum,sum/53))

numbers = [7,9,15,18,30,-3,7,12,-16,-12]

sum = 0
i = 0

print("짝수 번째 요소 : ",end = ' ')

while i < len(numbers):
  if i%2==0:
    sum = sum+numbers[i+1]
    print(numbers[i+1],end = ' ')
  i+=1

print()
print("합계",sum)

s = [64,89,100,85,77,58,79,67,96,87,87,36,82,98,84,76,63,69,53,22]

soo = 0
woo =0
mi =0
yang = 0
ga =0
i=0

while i<len(s):
  if s[i]>=90 and s[i]<=100:
    soo+=1
  elif s[i]>=80 and s[i]<=89:
    woo+=1
  elif s[i]>=70 and s[i]<=79:
    mi+=1
  elif s[i]>=60 and s[i]<=69:
    yang+=1
  else:
    ga+=1
  i+=1

print("수: %d명"%soo)
print("우: %d명"%woo)
print("미: %d명"%mi)
print("양: %d명"%yang)
print("가: %d명"%ga)