# -*- coding: utf-8 -*-
"""20613이정현_2차원 리스트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hPdRYgloazYLSXcc0NNkHSZn3D_qBa3a
"""

number = [[10,20,30],[40,50,60]]

print(number[0])
print(number[1])


print(number[0][0],number[0][1],number[0][2])
print(number[1][0],number[1][1],number[1][2])

number = [[10,20,30],[40,50,60,70,80]]

print(number[0][0],number[0][1],number[0][2])
print(number[1][0],number[1][1],number[1][2],number[1][3],number[1][4])

number = [[10,20,30],[40,50,60,70,80]]

for sub in number:
  for s in sub:
    print(s,end = ' ')
  print()

data = [[10,20],[30,40],[50,60],[70,80]]

for i in range(4):
  for s in range(2):
    print("data[%d][%d] = %d"%(i,s,data[i][s]))

string = [["원두커피","라떼","콜라"],["우동","국수","피자","파스타"]]

for i in range(len(string)):
  for s in range(len(string[i])):
    print(string[i][s],end = " ")
  print()

data = [[10,20,30],[40,50],[60,70,80,90]]
print(data)

for i in range(3):
    print(data[i][0])

score = [
          [88,76,92,98],
          [65,70,58,82],
          [82,80,78,88]
        ]

total = 0
totalsub = 0

for i in score:

  total =0
  for j in i:
    total += j
    totalsub += j
  print("총점은 %d 평균 %.2lf "%(total,total/4.0))

print("전체 총점은 %d 평균 %.2lf"%(totalsub,totalsub/12.0))

seats = [[0,0,0,0,0,0,0,0,0,0],\
         [0,0,0,0,0,0,0,0,0,0],\
         [0,0,0,0,0,0,0,0,0,0],\
         [1,1,1,0,0,0,0,0,1,0],\
         [0,0,0,0,0,1,0,0,0,0],\
         [0,1,0,0,0,1,0,1,0,0],\
         [0,0,0,0,0,0,1,0,0,0],\
         [1,0,1,0,0,0,0,0,0,1]]

for i in range(len(seats)):
  for j in range(len(seats[i])):
    if seats[i][j] == 0:
      print('%s'%'□',end = '')
    else:
      print('%s'%'■',end = '')
  print()
print('\n※ 예약 가능 : ■, 예약 불가 : □')



scores = [[96.84,80],[96,86,76],[76,95,83],[89,96,69],[83,86,79],[85,90,83]]

i = 0

while i < len(scores):
  j=0
  total = 0
  while j<len(scores[i]):
    total += scores[i][j]
    j+=1
  print("%d번째 학생의  합계:%d, 평균: %.2lf"%(i+1,total,total/3.0))
  i+=1

scores = [[96.84,80],[96,86,76],[76,95,83],[89,96,69],[83,86,79],[85,90,83]]

i = 0
for i in range(len(scores)):

  total = 0
  for j in range(len(scores[i])):
    total += scores[i][j]

  print("%d번째 학생의  합계:%d, 평균: %.2lf"%(i+1,total,total/3.0))

