# -*- coding: utf-8 -*-
"""20613이정현_루프의 활용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBMqqxSukchJYhBYhfZP1f2r0mMSLCZS
"""

for i in range(1,1001):
  print(i,end = '')
  if i== 10:
    break;

score = [92,86,68,120,56,72]
for i in range(1,6):
  if score[i] <0 or score[i] > 100:
    print("성적처리 끝")
    break;

  print(score[i])

score = [92,86,68,120,56,72]
for i in range(1,6):
  if score[i] <0 or score[i] > 100:
    continue;



  print(score[i])
print("성적처리 끝")

print("3 + 4  = ?")

while True:
  a = int(input("정답을 입력하시오: "))

  if a == 7:
    break;
print("참잘했어요")

while True:
  light = input("신호등 색상 입력")
  if light == "green":
    print("길을 건너세여")
    break;

i =1
total = 0

while True:
  total += i

  if total>50:
    print("합이 50보다 커지는 수는 %d이고 합은 %d입니다"%(i,total))
    break
  i+=1

for dan in range(2,10):
  print(dan,"단")
  for hang in range(2,10):
    print(dan,"*",hang,"=",dan*hang)
  print()

dan = 2

while dan<10:

  hang =1
  print(dan,"단")
  while hang <10:
    print(dan,"*",hang,"=",dan*hang)
    hang += 1
  print()

  dan+=1



for y in range(1,6):
  for x in range(1,y+1):
    print("*", end = '')
  print()

for i in range(1,7+1):
  for j in range(1,8):
    if i==j or i+j ==8:
      print("*",end = '')
    else:
      print(end = ' ')
  print()

cnt=0
n = int(input("수 입력: "))


for i in range(2,n+1):
  pn = 1

  for j in range(2,i):
    if i%j==0:
      pn = 0
      break

  if pn == 1:
    print('{:>5}'.format(i),sep = '',end = '')
    cnt+=1
    if cnt == 5:
      print()
      cnt =0