# -*- coding: utf-8 -*-
"""20613이정현_반복문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mw3uRRgvYQr3L2NcmasPWtSVKF3rB0Se
"""



"""### while문 16
~
*이탤릭체 텍스트*
"""

num = 0

while num<3:
  print("안녕허세요")
  num+=1

num = 0

while num<3:
  print(num+1,"번 학생의 성적을 처리한다.")
  num+=1

dan = int(input("원하는 단은? "))

i =1

while i<=9:
  print(dan,"*",i,"=",i*dan)
  i+=1

i =1
total = 0
while i<=10:
  total = total + i
  print("i의 값:",i,"=> 합계:",total)
  i+=1

i =150
total = 0
while i<=300:
  if i%2==1:
    total = total + i
  i+=1
print("sum = ",total)

print('-'*15)
print('섭씨  화씨')
print('-'*15)
c =-5

while c<=5:
  f = c*9.0/5.0 +32
  print("%5d  %5.1f "%(c,f))
  c+=1

print('-'*15)

n=10
to =1
while n>0:
  to = n*to
  n-=1

print("10! = ",to)

i=1

while i<=20:
  if i%2==0:
    print(i,end =' ')
  i+=1

i =10

while i <=50:
  if i%3!=0:
    print(i,end = ' ')
  i+=1

pw = ''

while pw != 'python':
  pw = input("암호 입력")
print("로그인 성공")

import random

cnt = 0
guess = 0
answer = random.randint(1,100)

print("1부터 100사이의 숫자를 맞추기")

while answer != guess:
  guess = int(input("숫자를 맞춰 보세요: "))
  cnt+=1
  if guess > answer:
    print("높음")
  elif guess<1xzanswer:
    print("낮음")

print("축하합니다","시도횟수 = ",cnt )