# -*- coding: utf-8 -*-
"""20613_이정현 dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zFfAt-MUP5n7Nqqxa8pSuERkGyPFXjZQ
"""

dic = {'boy':'소년', 'school':'학교','book':'책'}

print(dic)

dic = {'boy':'소년', 'school':'학교','book':'책'}

print(dic['boy'])
print(dic['book'])


print(dic['girl'])

dic = {'boy':'소년', 'school':'학교','book':'책'}

dic['boy'] = '남자아이'
dic['girl'] = '여자아이'

print(dic)

dic = {'boy':'소년', 'school':'학교','book':'책'}

del dic['boy']
del dic['book']

print(dic)

dic = {
    'name':"7D 건조 망고",
    'type':"당절임",
    'ingredient':["망고","설탕","메타중아황산나이트륨","치자황색소"],
    'origin':"필리핀"
}
print(dic)

dic = {
    'name':"7D 건조 망고",
    'type':"당절임",
    'ingredient':["망고","설탕","메타중아황산나이트륨","치자황색소"],
    'origin':"필리핀"
}

print("name: ",dic['name'])
print("type: ",dic['type'])
print("ingredient: ",dic['ingredient'])
print("origin: ",dic['origin'])

dic['name'] = "8D 건조 망고"
dic['price'] = 5000
del dic['ingredient']
print(dic)

animation = {}

print("요소 추가 이전:",animation)


animation['작가'] = '황미나'
animation['연재작'] = '이오니아의 푸른 별'
animation['최근작'] = '보톡스'
print("요소 추가 이후:",animation)

del animation['연재작']
print("요소 제거 이후:",animation)

rainbow = {'빨강':'red', "주황":'orange' , "노":'yellow' , "초":'green' , "파":'blue' , "남":'navy' , "보":'purple'}
print("초록색=",rainbow['초'])

rainbow['하얀색'] = 'white'
rainbow['주황'] = 'juwhang'

del rainbow['파']


print(rainbow)

li = [['boy','소년'],['school','학교'],['book','책']]

dic = dict(li)

print(dic)