# -*- coding: utf-8 -*-
"""20613이정현 리스트 컴프리헨션.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nptVq6KT1YeV2qxIyVlQJ5OOz0EWZbBQ
"""

[2*n for n in range(1,11)]

even1 = [2*n for n in range(1,51)]
even2 = [n+2 for n in range(0,99,2)]

print(even1)
print(even2)

li = []

for n in range(1,11):
  if n%3==0:
    li.append(n*n)

print(li)

numbers = [1,2,3,4,5]
result = [2*i for i in numbers if i%2!=0]
print(result)

v = [17,92,18,33,58,7,33,42]
max = v[0]

for i in range(1,len(v)):
  if v[i] > max:
    max = v[i]

print(max)

for i in [1,2,3]:
  for num in ['a','b','c']:
    print(num*i,end = ' ')

list_a = ["I","Study","python","language","!"]

for i in list_a:
  if len(i)>=3:
    print(i)

