# -*- coding: utf-8 -*-
"""20613 이정현p23 예제18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1noiLhbU0inGmfL9EzQj20BdU1lmdFAS6
"""

nums = [0,1,2,3,4,5,6,7,8,9]
print(nums[2:5:1])
print(nums[1:7:2])
print(nums[0:5:2])

nums = [0,1,2,3,4,5,6,7,8,9]
print(nums[0:5])
print(nums[0:7:2])
print(nums[0:5:2])

nums = [0,1,2,3,4,5,6,7,8,9]
print(nums[2:10])
print(nums[1:2])
print(nums[7:10])

nums = [0,1,2,3,4,5,6,7,8,9]
print(nums[2:5])
print(nums[1:7])
print(nums[0:5])

fruits = ['사과','오렌지','딸기','포도','감','키위','멜론','수박']

print(fruits)
print(fruits[0])
print(fruits[1:4])
print(fruits[2:])
print(fruits[-1])
print(fruits[-4:-2])
print(fruits[-3:])

mylist = list("PythonIsFun!")
print(mylist)
print(mylist[5:11])
print(mylist[-5:-2])
print(mylist[:4])
print(mylist[8:])

s = "python"
print(s[2])
print(s[-2])
print(s[1:4])

file = "20210505-104830.jpg"

print("촬영날짜:"+file[4:6]+"월"+file[6:8]+"일")
print("촬영시간:"+file[9:11]+"시"+file[11:13]+"일")
print("확장자:"+file[16:])

s = "차종: 코란도C, 제조사:쌍용, 배기량: 1988"
print(s[14:16])

jumin = "901231 - 1914983"
year = int(jumin[0:2])

if int(jumin[9:10])%2==0:
  gender = "여자"
else:
  gender = "남자"
print("{}년생 {}입니다.".format(year,gender))

