# -*- coding: utf-8 -*-
"""ex1_3/24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLA9XKNr1Y82eHDba9tlC_Kt5WoLqxt9
"""

print(1234)
print(12,34)
print(12+34)

#변수란 변하는 수가 저장되는 기억 공간
#저장한다=> 대입 연산자(=)
#정수 = integer =int


value = 1234

print(value)
print(value+100)
print(type(value))

#파이썬에서 문자데이터는 따옴표를 사용('',"")


print("강아지")
print("고양이")

a = "강아지"
b = "고양이"
print(a)
print(b)

print(a,b)

print(a,b,sep = "")

print(12,34,56,"정현서 과정근",sep = "~~")

a = "강아지"
b = "고영이"

print(a,end = " ")
print(b)

print(34,end = "^^")
print(78)

#
a =12
b = 34

print(a,b,sep = ",")

s  = "서울"
d = "대전"
g = "대구"
b = "부산"

print(s,d,g,b,sep="찍고 ")

print(12,34,56,sep = "^^",end = "-->")
print(78)

a = 13
b = 21
print(a,b)
print(a+b)
print(a,b,sep='')
print(a,b,end= '')

age = input('몇 살이세요?')
print(age)

name = input("이름이 뭐예요: ")

print("안녕하세요",name,"사마")

a = input("첫 번째 과일 입력: ")
b = input("두 번쨰 과일 입력: ")

print(a,"와",b,"은 내가 좋아하는 과일이다")

year = input("몇 년도?")
month = input("몇 월?")
day = input("몇 일?")

print(year,month,day,sep = ". ")

age = input("몇 살이세요?") # 항상 문자열로 저장됨
age = int(age)



print(age+age)

p = input("가격을 입력하세요:")
n = input("개수을 입력하세요:")


sum = int(p)*int(n)

print("총액은",sum,"원입니다")

print("김도은 여친..............")

