# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11FP6zZmFS9JdS0P-AU7gBDdkvlb1LZJB
"""

score = [1,2,3,4,5]
print(type(score))
tu = tuple(score)
print(type(tu))

li = list(tu)
print(li)
print(type(li))

dic = {'boy':'소년', 'school':'학교','book':'책'}

print(dic)
print(type(dic))
print(dic['boy'])

print(dic.keys())
print(type((dic.keys())))
print(dic.values())
print(type(dic.values()))
print(dic.items)
print(type(dic.items()))

sorted(dic)

dic1 = sorted(dic)
print(dic1)

dic2 = sorted(dic.keys())
print(dic2)

dic3 = sorted(dic.valaues())
print(dic3)

dic = {'boy':'소년', 'school':'학교','book':'책'}

for k in dic:
  print(k)

dic = {'boy':'소년', 'school':'학교','book':'책'}

for k in dic.keys():
  print(k)

dic = {'boy':'소년', 'school':'학교','book':'책'}

for k in dic.values():
  print(k)

dic = {'boy':'소년', 'school':'학교','book':'책'}

for k in dic.items():
  print(k)

dic = {'boy':'소년', 'school':'학교','book':'책'}

for k,i in dic.items():
  print(k, i)
  print(type(k),type(i))

