# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13QfEyyKZo-BqXdWDBdIXDOvbq_jm8D1h
"""

now = int(input("현재 키는?"))
goal = int (input("5개월 후의 목표 키는?"))
cm = (goal-now)/5





print("한달에", cm, "cm씩 성장해 보세요")

book = int(input("책 값?"))

discount = int(input("할인율"));
delivery = int(input("배송비"));

total = book-(book*discount/100)+delivery

print(total)

score1= int(input(""))
score2=int(input(""))
sum = score1+ score2

avg = sum/2

print(avg)

w =int(input(""))
h =int(input(""))

area = w*h/2
print(area);

kg = float(input(""))

pound = kg * 2.2046

print(pound)

print(5+ 2)
print(5 -2)
print(5 *2)
print(5 /2)
print(5 **2)
print(5 // 2)
print(5 %2)

x = 10%3
print(x)

y  = 7//3
print(y)

#ㄴ연산자 순위 곱셈과 난눗셈 > 덧셈과 뺄셈
# 동순위 경우 왼쪽에서 오르쪽으로 진행하면서 계선



a = 10
b = 20
c = a+(b*10)-(5/5)


print(c)
print(str(123)+'123')

x = 2**3

print(x)

y = 10**4
print(y)

#문자열
# +연산자 :연결
# *연산자 :반복

hello = '문자열'

print(hello)

s1 = '대한민국'
s2='화이팅'

print(s1+s2)
print(s1*5)

print(int('22'))

x = 10
#x = x+10
x+=1

print(x)

a= 20
a*=20
print(a)

b = 100

b/=10
print(b)

x = 3
y = 5


x*=x+y


print(x)

