# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3UuoIoMQ0Y0MhI1AXI6lToMGjts_xg4
"""

animals = ['토끼', '거북이','사자','호랑이']
for i in range(0,4):
  print(animals[i])



nums = [1,2,3,4]
nums.append(5)

nums.insert(2,99)

print(nums)

list1 = [1,2,3,4,5]
list2 = [10,11]

list1.extend(list2)
print(list1)

score = [88,95,70,100,99]
print("100의 위치: ",score.index(100)+1)
print(score.pop())
print(score.pop())
print(score.pop(1))
print(score)

score = [88,95,70,100,99]
score.remove(99)
print("99삭제후",score)
score.sort()
print("리스트 정렬 후",score)
score.sort(reverse = True)
print("거꾸로 정렬:",score)
score.clear()
print("리스트 삭제:",score)

list1 = ['a','bb','c','d','aaa','c','ddd','aaa','b','cc','d','aaa']
length = list1.count("aaa")
print(length)





