# -*- coding: utf-8 -*-
"""수행평가_20613이정현.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWBbuek-zDf06UE10h5Fv52_41-YMjgR
"""

for i in range(10,51,1):
  if(i%3==0):
    continue;
  print(i,end = ' ')

from random import *

you = randint(1,6)
play = 'y'
print("주사위 게임을 시작하겠습니다. \n")

while play == 'y':
  print("주사위를 던졌습니다 ")
  me = randint(1,6)
  you = randint(1,6)

  print("나:",me)
  print("너 :",you)

  if me>you:
    print("나의 승리")
  elif me<you:
    print("너의 승리")
  else:
    print("무승부")

  play = input("계속하려면 y를 입력하세요! ")

a = int(input("숫자 입력: "))

while a !=0:
  print(a % 10,end = "")
  a = a // 10

dan = 2

for i in range(1,10,1):
  print(dan," x ",i," = ",dan*i)

max_product = 0
max_i = 0

for i in range(1, 100):
    product = i * (100 - i)
    if product > max_product:
        max_product = product
        max_i = i

max_j = 100 - max_i
print(max_i, '*', max_j, '=', max_product)

n = int(input("정수를 입력하시오 : "))

for i in range(1,n+1):
  if n%i==0:
    print(i,end = ' ')

n = int(input("입력할 숫자 개수: "))
max = 0
maxi=0;
for i in range(0,n):
  a = int(input("숫자입력"))
  if a>max:
    max = a
    maxi =i+1

print("가장 큰 수는 ",maxi,"번째에 있습니다")

for i in range(4,101,4):
  print(i,end = ' ')
  if i%7==0:
    print()





n = int(input("숫자 입력:"))
cnt =0
for i in range(1,n+1,10):
  cnt+=1
print("일의 자리가 1인수는",cnt,"개")



s=0

print("3+4=?")

while s!=7:
  s = int(input("정답을 입력하시오"))

print("참 잘했어요")

print('I said "Hello" to you.')
print("Let's go.")

a = int(input("삼각형의 밑변 길이 : "))
b = int(input("삼각형의 높이 : "))
print("삼각형의 면적 :",a*b/2)

a = int(input("현재 시 : "))
b = int(input("현재 분 : "))
b+= 20
if(b >= 60):
  a += 1
  b -= 60
if(a > 23):
  a = 0
print("20분 뒤에는",str(a)+"시",str(b)+"분 입니다.")

a = int(input("숫자 입력: "))
if(a>=0):
  print(a)
else:
  print(a*-1)

id = str(input("아이디를 입력하세요: "))
lev = int(input("회원 레벨을 입력하세요.: "))
if(id=="admin" or lev == 1):
  print("관리자입니다.")
else:
  print("관리자가 아닙니다.")

a = int(input("첫 번째 수: "))
b = int(input("두 번째 수: "))
c = int(input("세 번째 수: "))

if(a>b and a>c):
  print(a)
elif(b>a and b>c):
  print(b)
else:
  print(c)

age = int(input("나이 입력: "))
if(0 <= age < 8):
  print("어린이")
elif(7 < age <= 13):
  print("초등학생")
elif(13 < age <= 16):
  print("중학생")
elif(16 < age <= 19):
  print("고등학생")
else:
  print("성인")

a = int(input("점수 입력: "))
if(a >= 90):
  print("A 등급")
elif(a >= 80):
  print("B 등급")
elif(a >= 70):
  print("C 등급")
else:
  print("F 등급")

a = int(input("숫자 입력: "))

if(a%3 == 0):
  if(a%5!=0):
    print("3의 배수")
  elif(a%5==0):
    print("3과 5의 공배수")
else:
  print("3의 배수 아님")

for i in range(1,21,2):
  print(i,end=" ")

sum = 0
for i in range(1,11,1):
  sum += i
  print("num의 값 :",i,"=> 합계 :",sum)

a = int(input("숫자 입력:"))
fac = 1
for i in range(1,a+1,1):
  fac *= i
print(str(a)+"!","=",str(fac))

import random
answer = random.randint(1,100)
count = 0
print("정답 :",answer)
print("1부터 100 사이의 숫자를 맞히기")
while True:
  count += 1
  guess = int(input("숫자를 맞혀 보세요 : "))
  if (answer == guess):
    print("축하합니다. 시도횟수 =",count)
    break
  elif(answer > guess):
    print("낮음")
  elif(answer < guess):
    print("높음")